<?php include '../include/header_sub_content.php'; ?>
<!--	시작 : 헤더	-->
<header class='ct-header'>
	<div class='w1600 str clear'>
		<h1 class='logo-div'><a href='../main/main_search.php'><img src='../images/common/logo_s.png' alt='로앤비'></a>
		</h1>
		<div class='c-right header-h'>
			<ul class='ct-hd-icon-ul'>
				<!-- 글자크기 -->
				<li class='btn-multi'>
					<button class='hd-btn'>
						<span class='icon icon-plus02 icon-w25'></span>
					</button>
					<button class='hd-btn'>
						<span class='icon icon-minus icon-w25'></span>
					</button>
					<p class='dis-b mt-5 txt'>글자크기</p>
				</li>
				<!-- 인쇄  -->
				<li class='btn-all str'>
					<button class='hd-btn dis-b' onclick="fn_add_class_on('#con-print-popup')">
						<span class='dis-b icon icon-printer icon-w25'></span>
						<span class='dis-b mt-5 txt'>인쇄</span>
					</button>
				</li>
				<!-- 파일저장  -->
				<li class='btn-all str'>
					<button class='hd-btn dis-b' onclick="fn_add_class_on('#con-file-down-popup')">
						<span class='n-i-file-down n-i-w25 n-i c-black'></span>
						<span class='dis-b mt-5 txt'>파일저장</span>
					</button>
				</li>
			</ul>
		</div>
	</div>
</header>
<!--	끝 : 헤더	-->
<!--	시작 : 본문	-->
<div class="ct-wrap lawyer-navigation">
	<div class="ct-center ct-all pr-0 border-r border-l">
		<div class='title-area'>
			<h2>사건별 부호문자의 부여에 관한 예규(재일 2003-1)</h2>
			<div class='txt02'>개정 2017.12.21 재판예규 제1677호</div>
			<input type='hidden' id='hdnPrintType' value='1'>
			<input type='hidden' id='hdnSignTabIndex' value='0'>
			<div id='tab_area' class='mgt20'>
				<a href='#' id='casesignTop1' class='on' onclick="initCaseview('1');">사건별 부호문자</a>
				<a href='#' id='casesignTop2' class='off' onclick="initCaseview('2');">예규 본문</a>
			</div>
		</div>
		<div class="navi-con-wrap clear">
			<div class="h-100p c-left ct-scroll w-100p">
				<div id='view_content' class='law case'>
					<div class='old_new  '>
						<ul class='sign_tab'>
							<li class='_this'>민사</li>
							<li>가사</li>
							<li>특허</li>
							<li>행정</li>
							<li>선거</li>
							<li>형사</li>
							<li>비송</li>
							<li>집행</li>
							<li>특별</li>
							<li>보호</li>
							<li>감치</li>
							<li>신청</li>
							<li>기타</li>
						</ul>
						<div class='case_sign' id='case_sign_0' style='display: block;'>
							<table summary='코드, 사건구분, 사건유형, 내용, 사건검색 제공 별 사건구분안내 표'>
								<caption>사건구분안내 민사</caption>
								<colgroup>
									<col width='20%'>
									<col width='20%'>
									<col width='60%'>
								</colgroup>
								<thead>
								<tr>
									<th>코드</th>
									<th>
										사건
										구분
									</th>
									<th>
										사건
										유형
									</th>
									<th>내용</th>
									<th>
										사건 검색 제공
									</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td>002</td>
									<td>가합</td>
									<td>민사</td>
									<td>
										<p>민사1심합의사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>001</td>
									<td>가단</td>
									<td>민사</td>
									<td>민사1심단독사건</td>
									<td>○</td>
								</tr>
								<tr>
									<td>003</td>
									<td>가소</td>
									<td>민사</td>
									<td>
										<p>민사소액사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>004</td>
									<td>나</td>
									<td>민사</td>
									<td>
										<p>민사항소사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>005</td>
									<td>다</td>
									<td>민사</td>
									<td>
										<p>민사상고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>007</td>
									<td>라</td>
									<td>민사</td>
									<td>
										<p>민사항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>009</td>
									<td>마</td>
									<td>민사</td>
									<td>
										<p>민사재항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>048</td>
									<td>그</td>
									<td>민사</td>
									<td>
										<p>민사특별항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>010</td>
									<td>바</td>
									<td>민사</td>
									<td>
										<p>민사준항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>021</td>
									<td>머</td>
									<td>민사</td>
									<td>
										<p>민사조정사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>011</td>
									<td>자</td>
									<td>민사</td>
									<td>
										<p>화해사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>012</td>
									<td>차</td>
									<td>민사</td>
									<td>독촉사건</td>
									<td>○</td>
								</tr>
								<tr>
									<td>020</td>
									<td>러</td>
									<td>민사</td>
									<td>
										<p>민사공조사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>051</td>
									<td>재가합</td>
									<td>민사</td>
									<td>
										<p>민사1심합의사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>050</td>
									<td>재가단</td>
									<td>민사</td>
									<td>
										<p>민사1심단독사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>052</td>
									<td>재가소</td>
									<td>민사</td>
									<td>
										<p>민사소액사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>053</td>
									<td>재나</td>
									<td>민사</td>
									<td>
										<p>민사항소사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>054</td>
									<td>재다</td>
									<td>민사</td>
									<td>
										<p>민사상고사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>168</td>
									<td>재라</td>
									<td>민사</td>
									<td>
										<p>민사항고사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>123</td>
									<td>재마</td>
									<td>민사</td>
									<td>
										<p>민사재항고사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>124</td>
									<td>재그</td>
									<td>민사</td>
									<td>
										<p>민사특별항고사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>064</td>
									<td>재머</td>
									<td>민사</td>
									<td>
										<p>민사조정사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>134</td>
									<td>재자</td>
									<td>민사</td>
									<td>
										<p>화해사건재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>058</td>
									<td>재차</td>
									<td>민사</td>
									<td>
										<p>독촉사건재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>067</td>
									<td>준재가합</td>
									<td>민사</td>
									<td>
										<p>민사1심합의사건준재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>066</td>
									<td>준재가단</td>
									<td>민사</td>
									<td>
										<p>민사1심단독사건준재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>068</td>
									<td>준재가소</td>
									<td>민사</td>
									<td>
										<p>민사소액사건준재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>105</td>
									<td>준재나</td>
									<td>민사</td>
									<td>
										<p>민사항소사건준재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>170</td>
									<td>준재다</td>
									<td>민사</td>
									<td>
										<p>민사상고사건준재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>174</td>
									<td>준재라</td>
									<td>민사</td>
									<td>
										<p>민사항고사건준재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>125</td>
									<td>준재자</td>
									<td>민사</td>
									<td>
										<p>화해사건준재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>106</td>
									<td>준재머</td>
									<td>민사</td>
									<td>
										<p>민사조정사건준재심</p>
									</td>
									<td>○</td>
								</tr>
								</tbody>
							</table>
						</div>

						<div class='case_sign' id='case_sign_1'>
							<table summary='코드, 사건구분, 사건유형, 내용, 사건검색 제공 별 사건구분안내 표'>
								<caption>사건구분안내 가사</caption>
								<colgroup>
									<col width='20%'>
									<col width='20%'>
									<col width='60%'>
									<col width='43%'>
									<col width='15%'>
								</colgroup>
								<thead>
								<tr>
									<th>코드</th>
									<th>
										사건
										구분
									</th>
									<th>
										사건
										유형
									</th>
									<th>내용</th>
									<th>
										사건
										검색
										제공
									</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td>160</td>
									<td>준재너단</td>
									<td>가사</td>
									<td>
										<p>조정 단독 사건 준재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>161</td>
									<td>준재너합</td>
									<td>가사</td>
									<td>
										<p>조정 합의 사건 준재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>023</td>
									<td>드</td>
									<td>가사</td>
									<td>
										<p>가사1심사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>151</td>
									<td>드합</td>
									<td>가사</td>
									<td>
										<p>가사1심합의사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>150</td>
									<td>드단</td>
									<td>가사</td>
									<td>
										<p>가사1심단독사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>024</td>
									<td>르</td>
									<td>가사</td>
									<td>
										<p>가사항소사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>025</td>
									<td>므</td>
									<td>가사</td>
									<td>
										<p>가사상고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>026</td>
									<td>브</td>
									<td>가사</td>
									<td>
										<p>가사항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>027</td>
									<td>스</td>
									<td>가사</td>
									<td>
										<p>가사재항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>110</td>
									<td>으</td>
									<td>가사</td>
									<td>
										<p>가사특별항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>029</td>
									<td>너</td>
									<td>가사</td>
									<td>
										<p>가사조정사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>030</td>
									<td>츠</td>
									<td>가사</td>
									<td>
										<p>가사공조사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>028</td>
									<td>즈</td>
									<td>가사</td>
									<td>
										<p>가사가압류,가처분등사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>178</td>
									<td>즈합</td>
									<td>가사</td>
									<td>
										<p>가사가압류,가처분등합의사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>177</td>
									<td>즈단</td>
									<td>가사</td>
									<td>
										<p>가사가압류,가처분등단독사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>211</td>
									<td>즈기</td>
									<td>가사</td>
									<td>
										<p>기타가사신청사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>022</td>
									<td>느</td>
									<td>가사</td>
									<td>
										<p>가사비송사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>163</td>
									<td>느합</td>
									<td>가사</td>
									<td>
										<p>가사비송합의사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>162</td>
									<td>느단</td>
									<td>가사</td>
									<td>
										<p>가사비송단독사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>059</td>
									<td>재드</td>
									<td>가사</td>
									<td>
										<p>가사1심사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>153</td>
									<td>재드합</td>
									<td>가사</td>
									<td>
										<p>가사1심합의사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>152</td>
									<td>재드단</td>
									<td>가사</td>
									<td>
										<p>가사1심단독사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>060</td>
									<td>재르</td>
									<td>가사</td>
									<td>
										<p>가사항소사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>061</td>
									<td>재므</td>
									<td>가사</td>
									<td>
										<p>가사상고사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>146</td>
									<td>재브</td>
									<td>가사</td>
									<td>
										<p>가사항고사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>147</td>
									<td>재스</td>
									<td>가사</td>
									<td>
										<p>가사재항고사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>183</td>
									<td>재너</td>
									<td>가사</td>
									<td>
										<p>가사조정사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>226</td>
									<td>재즈합</td>
									<td>가사</td>
									<td>
										<p>가사가압류,가처분등합의사건재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>225</td>
									<td>재즈단</td>
									<td>가사</td>
									<td>
										<p>가사가압류,가처분등단독사건재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>251</td>
									<td>재즈기</td>
									<td>가사</td>
									<td>
										<p>기타가사신청사건재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>165</td>
									<td>재느합</td>
									<td>가사</td>
									<td>
										<p>가사비송합의사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>164</td>
									<td>재느단</td>
									<td>가사</td>
									<td>
										<p>가사비송단독사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>143</td>
									<td>준재드</td>
									<td>가사</td>
									<td>
										<p>가사1심사건준재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>155</td>
									<td>준재드합</td>
									<td>가사</td>
									<td>
										<p>가사1심합의사건준재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>154</td>
									<td>준재드단</td>
									<td>가사</td>
									<td>
										<p>가사1심단독사건준재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>144</td>
									<td>준재르</td>
									<td>가사</td>
									<td>
										<p>가사항소사건준재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>145</td>
									<td>준재므</td>
									<td>가사</td>
									<td>
										<p>가사상고사건준재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>148</td>
									<td>준재브</td>
									<td>가사</td>
									<td>
										<p>가사항고사건준재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>149</td>
									<td>준재스</td>
									<td>가사</td>
									<td>
										<p>가사재항고사건준재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>252</td>
									<td>준재즈기</td>
									<td>가사</td>
									<td>
										<p>기타가사신청사건준재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>167</td>
									<td>준재느합</td>
									<td>가사</td>
									<td>
										<p>가사비송합의사건준재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>166</td>
									<td>준재느단</td>
									<td>가사</td>
									<td>
										<p>가사비송단독사건준재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>430</td>
									<td>인</td>
									<td>가사</td>
									<td>
										<p>인신보호사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>431</td>
									<td>인라</td>
									<td>가사</td>
									<td>
										<p>인신보호항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>432</td>
									<td>인마</td>
									<td>가사</td>
									<td>
										<p>인신보호재항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>433</td>
									<td>인카</td>
									<td>가사</td>
									<td>
										<p>인신보호신청사건</p>
									</td>
									<td>○</td>
								</tr>
								</tbody>
							</table>
						</div>
						<div class='case_sign' id='case_sign_2'>
							<table summary='코드, 사건구분, 사건유형, 내용, 사건검색 제공 별 사건구분안내 표'>
								<caption>사건구분안내 특허</caption>
								<colgroup>
									<col width='20%'>
									<col width='20%'>
									<col width='60%'>
									<col width='43%'>
									<col width='15%'>
								</colgroup>
								<thead>
								<tr>
									<th>코드</th>
									<th>
										사건
										구분
									</th>
									<th>
										사건
										유형
									</th>
									<th>내용</th>
									<th>
										사건
										검색
										제공
									</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td>129</td>
									<td>허</td>
									<td>특허</td>
									<td>
										<p>특허1심사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>046</td>
									<td>후</td>
									<td>특허</td>
									<td>
										<p>특허상고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>032</td>
									<td>흐</td>
									<td>특허</td>
									<td>
										<p>특허재항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>130</td>
									<td>히</td>
									<td>특허</td>
									<td>
										<p>특허특별(준)항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>131</td>
									<td>카허</td>
									<td>특허</td>
									<td>
										<p>특허신청사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>132</td>
									<td>재허</td>
									<td>특허</td>
									<td>
										<p>특허1심사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>047</td>
									<td>재후</td>
									<td>특허</td>
									<td>
										<p>특허상고사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>275</td>
									<td>재흐</td>
									<td>특허</td>
									<td>
										<p>특허재항고사건재심</p>
									</td>
									<td>X</td>
								</tr>
								</tbody>
							</table>
						</div>
						<div class='case_sign' id='case_sign_3'>
							<table summary='코드, 사건구분, 사건유형, 내용, 사건검색 제공 별 사건구분안내 표'>
								<caption>사건구분안내 행정</caption>
								<colgroup>
									<col width='20%'>
									<col width='20%'>
									<col width='60%'>
									<col width='43%'>
									<col width='15%'>
								</colgroup>
								<thead>
								<tr>
									<th>코드</th>
									<th>
										사건
										구분
									</th>
									<th>
										사건
										유형
									</th>
									<th>내용</th>
									<th>
										사건
										검색
										제공
									</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td>033</td>
									<td>구</td>
									<td>행정</td>
									<td>행정1심사건</td>
									<td>○</td>
								</tr>
								<tr>
									<td>034</td>
									<td>누</td>
									<td>행정</td>
									<td>행정항소사건</td>
									<td>○</td>
								</tr>
								<tr>
									<td>035</td>
									<td>두</td>
									<td>행정</td>
									<td>행정상고사건</td>
									<td>○</td>
								</tr>
								<tr>
									<td>036</td>
									<td>루</td>
									<td>행정</td>
									<td>행정항고사건</td>
									<td>○</td>
								</tr>
								<tr>
									<td>037</td>
									<td>부</td>
									<td>행정</td>
									<td>행정특별항고사건</td>
									<td>○</td>
								</tr>
								<tr>
									<td>056</td>
									<td>재구</td>
									<td>행정</td>
									<td>행정1심사건재심</td>
									<td>○</td>
								</tr>
								<tr>
									<td>057</td>
									<td>재누</td>
									<td>행정</td>
									<td>행정항소사건재심</td>
									<td>○</td>
								</tr>
								<tr>
									<td>126</td>
									<td>사</td>
									<td>행정</td>
									<td>행정준항고사건</td>
									<td>○</td>
								</tr>
								<tr>
									<td>127</td>
									<td>아</td>
									<td>행정</td>
									<td>행정신청사건</td>
									<td>○</td>
								</tr>
								<tr>
									<td>128</td>
									<td>재두</td>
									<td>행정</td>
									<td>행정상고사건재심</td>
									<td>○</td>
								</tr>
								<tr>
									<td>133</td>
									<td>무</td>
									<td>행정</td>
									<td>행정재항고사건</td>
									<td>○</td>
								</tr>
								<tr>
									<td>139</td>
									<td>재아</td>
									<td>행정</td>
									<td>행정신청사건재심</td>
									<td>○</td>
								</tr>
								<tr>
									<td>140</td>
									<td>준재구</td>
									<td>행정</td>
									<td>행정1심사건준재심</td>
									<td>○</td>
								</tr>
								<tr>
									<td>141</td>
									<td>준재누</td>
									<td>행정</td>
									<td>행정항소사건준재심</td>
									<td>○</td>
								</tr>
								<tr>
									<td>142</td>
									<td>준재아</td>
									<td>행정</td>
									<td>행정신청사건준재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>169</td>
									<td>준재두</td>
									<td>행정</td>
									<td>행정상고사건준재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>184</td>
									<td>재무</td>
									<td>행정</td>
									<td>행정재항고사건재심</td>
									<td>○</td>
								</tr>
								<tr>
									<td>186</td>
									<td>준재루</td>
									<td>행정</td>
									<td>행정신청항고사건준재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>188</td>
									<td>재루</td>
									<td>행정</td>
									<td>행정신청항고사건재심</td>
									<td>○</td>
								</tr>
								<tr>
									<td>194</td>
									<td>구단</td>
									<td>행정</td>
									<td>행정1심재정단독사건</td>
									<td>○</td>
								</tr>
								<tr>
									<td>195</td>
									<td>구합</td>
									<td>행정</td>
									<td>행정1심사건</td>
									<td>○</td>
								</tr>
								<tr>
									<td>196</td>
									<td>재구단</td>
									<td>행정</td>
									<td>행정1심재정단독사건재심</td>
									<td>○</td>
								</tr>
								<tr>
									<td>197</td>
									<td>재구합</td>
									<td>행정</td>
									<td>행정1심사건재심</td>
									<td>○</td>
								</tr>
								<tr>
									<td>198</td>
									<td>준재구단</td>
									<td>행정</td>
									<td>행정1심재정단독사건준재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>199</td>
									<td>준재구합</td>
									<td>행정</td>
									<td>행정1심사건준재심</td>
									<td>X</td>
								</tr>
								</tbody>
							</table>
						</div>
						<div class='case_sign' id='case_sign_4'>
							<table summary='코드, 사건구분, 사건유형, 내용, 사건검색 제공 별 사건구분안내 표'>
								<caption>사건구분안내 선거</caption>
								<colgroup>
									<col width='20%'>
									<col width='20%'>
									<col width='60%'>
									<col width='43%'>
									<col width='15%'>
								</colgroup>
								<thead>
								<tr>
									<th>코드</th>
									<th>
										사건
										구분
									</th>
									<th>
										사건
										유형
									</th>
									<th>내용</th>
									<th>
										사건
										검색
										제공
									</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td>038</td>
									<td>수</td>
									<td>선거특별</td>
									<td>선거소송사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>040</td>
									<td>재수</td>
									<td>선거특별</td>
									<td>선거소송사건재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>041</td>
									<td>주</td>
									<td>선거특별</td>
									<td>선거신청사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>043</td>
									<td>추</td>
									<td>선거특별</td>
									<td>특수소송사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>044</td>
									<td>쿠</td>
									<td>선거특별</td>
									<td>특수신청사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>045</td>
									<td>재추</td>
									<td>선거특별</td>
									<td>특수소송사건재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>062</td>
									<td>우</td>
									<td>선거특별</td>
									<td>선거상고사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>063</td>
									<td>재우</td>
									<td>선거특별</td>
									<td>선거상고사건재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>109</td>
									<td>수흐</td>
									<td>선거특별</td>
									<td>선거항고(재항고,준항고,특별항고)사건</td>
									<td>○</td>
								</tr>
								</tbody>
							</table>
						</div>
						<div class='case_sign' id='case_sign_5'>
							<table summary='코드, 사건구분, 사건유형, 내용, 사건검색 제공 별 사건구분안내 표'>
								<caption>사건구분안내 형사</caption>
								<colgroup>
									<col width='20%'>
									<col width='20%'>
									<col width='60%'>
									<col width='43%'>
									<col width='15%'>
								</colgroup>
								<thead>
								<tr>
									<th>코드</th>
									<th>
										사건
										구분
									</th>
									<th>
										사건
										유형
									</th>
									<th>내용</th>
									<th>
										사건
										검색
										제공
									</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td>075</td>
									<td>고합</td>
									<td>형사</td>
									<td>
										<p>형사1심합의사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>077</td>
									<td>고단</td>
									<td>형사</td>
									<td>
										<p>형사1심단독사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>230</td>
									<td>고정</td>
									<td>형사</td>
									<td>
										<p>약식정재청구1심단독사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>078</td>
									<td>고약</td>
									<td>형사</td>
									<td>
										<p>약식사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>079</td>
									<td>노</td>
									<td>형사</td>
									<td>
										<p>형사항소사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>081</td>
									<td>도</td>
									<td>형사</td>
									<td>
										<p>형사상고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>083</td>
									<td>로</td>
									<td>형사</td>
									<td>
										<p>형사항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>085</td>
									<td>모</td>
									<td>형사</td>
									<td>
										<p>형사재항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>088</td>
									<td>오</td>
									<td>형사</td>
									<td>
										<p>비상상고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>087</td>
									<td>보</td>
									<td>형사</td>
									<td>
										<p>형사준항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>093</td>
									<td>코</td>
									<td>형사</td>
									<td>
										<p>형사보상청구사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>090</td>
									<td>조</td>
									<td>형사</td>
									<td>
										<p>즉결심판사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>094</td>
									<td>토</td>
									<td>형사</td>
									<td>
										<p>형사공조사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>091</td>
									<td>초</td>
									<td>형사</td>
									<td>
										<p>형사신청사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>204</td>
									<td>초적</td>
									<td>형사</td>
									<td>
										<p>체포,구속적부심사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>205</td>
									<td>초보</td>
									<td>형사</td>
									<td>
										<p>보석사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>206</td>
									<td>초기</td>
									<td>형사</td>
									<td>
										<p>기타형사신청사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>076</td>
									<td>감고</td>
									<td>형사</td>
									<td>
										<p>치료감호1심사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>080</td>
									<td>감노</td>
									<td>형사</td>
									<td>
										<p>치료감호항소사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>082</td>
									<td>감도</td>
									<td>형사</td>
									<td>
										<p>치료감호상고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>084</td>
									<td>감로</td>
									<td>형사</td>
									<td>
										<p>치료감호항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>086</td>
									<td>감모</td>
									<td>형사</td>
									<td>
										<p>치료감호재항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>089</td>
									<td>감오</td>
									<td>형사</td>
									<td>
										<p>치료감호비상상고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>095</td>
									<td>감토</td>
									<td>형사</td>
									<td>
										<p>치료감호공조사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>092</td>
									<td>감초</td>
									<td>형사</td>
									<td>
										<p>치료감호신청사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>112</td>
									<td>재고합</td>
									<td>형사</td>
									<td>
										<p>형사1심합의사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>113</td>
									<td>재고단</td>
									<td>형사</td>
									<td>
										<p>형사1심단독사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>231</td>
									<td>재고정</td>
									<td>형사</td>
									<td>
										<p>약식정재청구1심단독사건(재심)</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>114</td>
									<td>재고약</td>
									<td>형사</td>
									<td>
										<p>약식사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>115</td>
									<td>재노</td>
									<td>형사</td>
									<td>
										<p>형사항소사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>116</td>
									<td>재도</td>
									<td>형사</td>
									<td>
										<p>형사상고사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>117</td>
									<td>재감고</td>
									<td>형사</td>
									<td>
										<p>치료감호1심사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>118</td>
									<td>재감노</td>
									<td>형사</td>
									<td>
										<p>치료감호항소사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>119</td>
									<td>재감도</td>
									<td>형사</td>
									<td>
										<p>치료감호상고사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>234</td>
									<td>고약전</td>
									<td>전자약식</td>
									<td>
										<p>전자약식사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>235</td>
									<td>초사</td>
									<td>형사</td>
									<td>
										<p>사회봉사허가청구사건/사회봉사허가취소청구사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>264</td>
									<td>전로</td>
									<td>형사</td>
									<td>
										<p>부착명령항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>269</td>
									<td>전초</td>
									<td>형사</td>
									<td>
										<p>부착명령신청사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>270</td>
									<td>전모</td>
									<td>형사</td>
									<td>
										<p>부착명령재항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>360</td>
									<td>치고</td>
									<td>형사</td>
									<td>
										<p>치료명령1심사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>361</td>
									<td>치노</td>
									<td>형사</td>
									<td>
										<p>치료명령항소사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>362</td>
									<td>치도</td>
									<td>형사</td>
									<td>
										<p>치료명령상고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>363</td>
									<td>치오</td>
									<td>형사</td>
									<td>
										<p>치료명령비상상고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>364</td>
									<td>치초</td>
									<td>형사</td>
									<td>
										<p>치료명령신청(치료기간연장, 준수사항추가·변경·삭제청구)사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>365</td>
									<td>초치</td>
									<td>형사</td>
									<td>
										<p>성폭력수형자치료명령1심사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>366</td>
									<td>치로</td>
									<td>형사</td>
									<td>
										<p>치료명령항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>367</td>
									<td>치모</td>
									<td>형사</td>
									<td>
										<p>치료명령재항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>422</td>
									<td>초재</td>
									<td>형사</td>
									<td>
										<p>재정신청사건/재정신청 비용지급신청사건</p>
									</td>
									<td>○</td>
								</tr>
								</tbody>
							</table>
						</div>
						<div class='case_sign' id='case_sign_6'>
							<table summary='코드, 사건구분, 사건유형, 내용, 사건검색 제공 별 사건구분안내 표'>
								<caption>사건구분안내 비송</caption>
								<colgroup>
									<col width='20%'>
									<col width='20%'>
									<col width='60%'>
									<col width='43%'>
									<col width='15%'>
								</colgroup>
								<thead>
								<tr>
									<th>코드</th>
									<th>
										사건
										구분
									</th>
									<th>
										사건
										유형
									</th>
									<th>내용</th>
									<th>
										사건
										검색
										제공
									</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td>215</td>
									<td>비합</td>
									<td>비송도산</td>
									<td>
										<p>비송합의사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>216</td>
									<td>비단</td>
									<td>비송도산</td>
									<td>
										<p>비송단독사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>015</td>
									<td>파</td>
									<td>비송도산</td>
									<td>
										<p>비송사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>207</td>
									<td>파합</td>
									<td>비송도산</td>
									<td>
										<p>비송합의사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>208</td>
									<td>파단</td>
									<td>비송도산</td>
									<td>
										<p>비송단독사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>292</td>
									<td>회합</td>
									<td>비송도산</td>
									<td>
										<p>회생합의사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>291</td>
									<td>회단</td>
									<td>비송도산</td>
									<td>
										<p>회생단독사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>293</td>
									<td>회확</td>
									<td>비송도산</td>
									<td>
										<p>회생채권ㆍ회생담보권조사확정사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>294</td>
									<td>회기</td>
									<td>비송도산</td>
									<td>
										<p>기타회생관련신청사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>017</td>
									<td>하</td>
									<td>비송도산</td>
									<td>
										<p>파산사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>209</td>
									<td>하합</td>
									<td>비송도산</td>
									<td>
										<p>파산합의사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>210</td>
									<td>하단</td>
									<td>비송도산</td>
									<td>
										<p>파산단독사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>295</td>
									<td>하확</td>
									<td>비송도산</td>
									<td>
										<p>파산채권조사확정사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>214</td>
									<td>하면</td>
									<td>비송도산</td>
									<td>
										<p>면책사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>296</td>
									<td>하기</td>
									<td>비송도산</td>
									<td>
										<p>기타파산ㆍ면책관련신청사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>256</td>
									<td>하보</td>
									<td>비송도산</td>
									<td>
										<p>파산보전처분사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>253</td>
									<td>개회</td>
									<td>비송도산</td>
									<td>
										<p>개인회생사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>254</td>
									<td>개확</td>
									<td>비송도산</td>
									<td>
										<p>개인회생채권조사확정사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>290</td>
									<td>개기</td>
									<td>비송도산</td>
									<td>
										<p>기타개인회생관련신청사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>255</td>
									<td>개보</td>
									<td>비송도산</td>
									<td>
										<p>개인회생보전처분사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>297</td>
									<td>국승</td>
									<td>비송도산</td>
									<td>
										<p>국제도산승인사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>298</td>
									<td>국지</td>
									<td>비송도산</td>
									<td>
										<p>국제도산지원사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>179</td>
									<td>과</td>
									<td>비송도산</td>
									<td>
										<p>과태료사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>180</td>
									<td>회</td>
									<td>비송도산</td>
									<td>
										<p>회사정리사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>258</td>
									<td>회보</td>
									<td>비송도산</td>
									<td>
										<p>회사정리보전처분사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>203</td>
									<td>책</td>
									<td>비송도산</td>
									<td>
										<p>선박,유류등책임제한사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>181</td>
									<td>선</td>
									<td>비송도산</td>
									<td>
										<p>선박소유자등의책임제한사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>182</td>
									<td>유</td>
									<td>비송도산</td>
									<td>
										<p>유류오염손해배상책임제한사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>271</td>
									<td>재비합</td>
									<td>비송도산</td>
									<td>
										<p>비송합의사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>272</td>
									<td>재비단</td>
									<td>비송도산</td>
									<td>
										<p>비송단독사건재심</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>175</td>
									<td>재하</td>
									<td>비송도산</td>
									<td>
										<p>파산사건재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>218</td>
									<td>재과</td>
									<td>비송도산</td>
									<td>
										<p>과태료사건재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>176</td>
									<td>준재하</td>
									<td>비송도산</td>
									<td>
										<p>파산사건준재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>223</td>
									<td>준재과</td>
									<td>비송도산</td>
									<td>
										<p>과태료사건준재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>018</td>
									<td>거</td>
									<td>비송도산</td>
									<td>
										<p>도산화의사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>202</td>
									<td>화</td>
									<td>비송도산</td>
									<td>
										<p>도산화의사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>257</td>
									<td>화보</td>
									<td>비송도산</td>
									<td>
										<p>도산화의보전처분사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>302</td>
									<td>간회단</td>
									<td>비송도산</td>
									<td>
										<p>간이회생단독사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>303</td>
									<td>간회합</td>
									<td>비송도산</td>
									<td>
										<p>간이회생합의사건</p>
									</td>
									<td>○</td>
								</tr>
								</tbody>
							</table>
						</div>
						<div class='case_sign' id='case_sign_7'>
							<table summary='코드, 사건구분, 사건유형, 내용, 사건검색 제공 별 사건구분안내 표'>
								<caption>사건구분안내 집행</caption>
								<colgroup>
									<col width='20%'>
									<col width='20%'>
									<col width='60%'>
									<col width='43%'>
									<col width='15%'>
								</colgroup>
								<thead>
								<tr>
									<th>코드</th>
									<th>
										사건
										구분
									</th>
									<th>
										사건
										유형
									</th>
									<th>내용</th>
									<th>
										사건
										검색
										제공
									</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td>013</td>
									<td>타경</td>
									<td>집행</td>
									<td>부동산등경매사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>014</td>
									<td>타기</td>
									<td>집행</td>
									<td>기타집행사건</td>
									<td>○</td>
								</tr>
								<tr>
									<td>120</td>
									<td>타</td>
									<td>집행</td>
									<td>집행사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>122</td>
									<td>재타경</td>
									<td>집행</td>
									<td>부동산등경매사건재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>185</td>
									<td>준재타경</td>
									<td>집행</td>
									<td>부동산등경매사건준재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>200</td>
									<td>타채</td>
									<td>집행</td>
									<td>채권등집행사건</td>
									<td>○</td>
								</tr>
								<tr>
									<td>224</td>
									<td>재타기</td>
									<td>집행</td>
									<td>기타집행사건재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>601</td>
									<td>본</td>
									<td>집행</td>
									<td>동산경매, 부동산인도명도철거 등</td>
									<td>X</td>
								</tr>
								<tr>
									<td>602</td>
									<td>가</td>
									<td>집행</td>
									<td>동산가압류, 동산가처분, 부동산가처분</td>
									<td>X</td>
								</tr>
								<tr>
									<td>603</td>
									<td>징</td>
									<td>집행</td>
									<td>징수</td>
									<td>X</td>
								</tr>
								</tbody>
							</table>
						</div>
						<div class='case_sign' id='case_sign_8'>
							<table summary='코드, 사건구분, 사건유형, 내용, 사건검색 제공 별 사건구분안내 표'>
								<caption>사건구분안내 특별</caption>
								<colgroup>
									<col width='20%'>
									<col width='20%'>
									<col width='60%'>
									<col width='43%'>
									<col width='15%'>
								</colgroup>
								<thead>
								<tr>
									<th>코드</th>
									<th>
										사건
										구분
									</th>
									<th>
										사건
										유형
									</th>
									<th>내용</th>
									<th>
										사건
										검색
										제공
									</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td>038</td>
									<td>수</td>
									<td>선거특별</td>
									<td>선거소송사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>040</td>
									<td>재수</td>
									<td>선거특별</td>
									<td>선거소송사건재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>041</td>
									<td>주</td>
									<td>선거특별</td>
									<td>선거신청사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>043</td>
									<td>추</td>
									<td>선거특별</td>
									<td>특수소송사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>044</td>
									<td>쿠</td>
									<td>선거특별</td>
									<td>특수신청사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>045</td>
									<td>재추</td>
									<td>선거특별</td>
									<td>특수소송사건재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>062</td>
									<td>우</td>
									<td>선거특별</td>
									<td>선거상고사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>063</td>
									<td>재우</td>
									<td>선거특별</td>
									<td>선거상고사건재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>109</td>
									<td>수흐</td>
									<td>선거특별</td>
									<td>선거항고(재항고,준항고,특별항고)사건</td>
									<td>○</td>
								</tr>
								</tbody>
							</table>
						</div>
						<div class='case_sign' id='case_sign_9'>
							<table summary='코드, 사건구분, 사건유형, 내용, 사건검색 제공 별 사건구분안내 표'>
								<caption>사건구분안내 보호</caption>
								<colgroup>
									<col width='20%'>
									<col width='20%'>
									<col width='60%'>
									<col width='43%'>
									<col width='15%'>
								</colgroup>
								<thead>
								<tr>
									<th>코드</th>
									<th>
										사건
										구분
									</th>
									<th>
										사건
										유형
									</th>
									<th>내용</th>
									<th>
										사건
										검색
										제공
									</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td>098</td>
									<td>푸</td>
									<td>보호</td>
									<td>
										<p>소년보호사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>099</td>
									<td>크</td>
									<td>보호</td>
									<td>
										<p>소년보호항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>111</td>
									<td>트</td>
									<td>보호</td>
									<td>
										<p>소년보호재항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>187</td>
									<td>푸초</td>
									<td>보호</td>
									<td>
										<p>소년보호신청사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>135</td>
									<td>버</td>
									<td>보호</td>
									<td>
										<p>가정보호사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>136</td>
									<td>서</td>
									<td>보호</td>
									<td>
										<p>가정보호항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>137</td>
									<td>어</td>
									<td>보호</td>
									<td>
										<p>가정보호재항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>138</td>
									<td>저</td>
									<td>보호</td>
									<td>
										<p>가정보호신청사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>260</td>
									<td>성</td>
									<td>보호</td>
									<td>
										<p>성매매관련보호사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>261</td>
									<td>성로</td>
									<td>보호</td>
									<td>
										<p>성매매관련보호항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>262</td>
									<td>성모</td>
									<td>보호</td>
									<td>
										<p>성매매관련보호재항고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>263</td>
									<td>성초</td>
									<td>보호</td>
									<td>
										<p>성매매관련보호신청사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>436</td>
									<td>처</td>
									<td>보호</td>
									<td>
										<p>피해자보호명령사건</p>
									</td>
									<td>○</td>
								</tr>
								</tbody>
							</table>
						</div>
						<div class='case_sign' id='case_sign_10'>
							<table summary='코드, 사건구분, 사건유형, 내용, 사건검색 제공 별 사건구분안내 표'>
								<caption>사건구분안내 감치</caption>
								<colgroup>
									<col width='20%'>
									<col width='20%'>
									<col width='60%'>
									<col width='43%'>
									<col width='15%'>
								</colgroup>
								<thead>
								<tr>
									<th>코드</th>
									<th>
										사건
										구분
									</th>
									<th>
										사건
										유형
									</th>
									<th>내용</th>
									<th>
										사건
										검색
										제공
									</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td>100</td>
									<td>정</td>
									<td>감치</td>
									<td>감치,과태료</td>
									<td>X</td>
								</tr>
								<tr>
									<td>101</td>
									<td>정로</td>
									<td>감치</td>
									<td>법정질서위반감치등항고사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>103</td>
									<td>정모</td>
									<td>감치</td>
									<td>법정질서위반감치등재항고사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>240</td>
									<td>정가</td>
									<td>감치</td>
									<td>증인감치사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>241</td>
									<td>정명</td>
									<td>감치</td>
									<td>채무자감치사건</td>
									<td>○</td>
								</tr>
								<tr>
									<td>242</td>
									<td>정라</td>
									<td>감치</td>
									<td>증인·채무자감치항고사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>243</td>
									<td>정마</td>
									<td>감치</td>
									<td>증인·채무자감치재항고사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>244</td>
									<td>정고</td>
									<td>감치</td>
									<td>법정질서위반감치등사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>245</td>
									<td>정드</td>
									<td>감치</td>
									<td>의무불이행자감치등사건</td>
									<td>○</td>
								</tr>
								<tr>
									<td>246</td>
									<td>정브</td>
									<td>감치</td>
									<td>의무불이행자감치등항고사건</td>
									<td>○</td>
								</tr>
								<tr>
									<td>247</td>
									<td>정스</td>
									<td>감치</td>
									<td>의무불이행자감치등재항고사건</td>
									<td>○</td>
								</tr>
								<tr>
									<td>248</td>
									<td>정기</td>
									<td>감치</td>
									<td>기타감치신청사건</td>
									<td>X</td>
								</tr>
								<tr>
									<td>280</td>
									<td>재정가</td>
									<td>감치</td>
									<td>증인감치사건재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>281</td>
									<td>재정명</td>
									<td>감치</td>
									<td>채무자감치사건재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>282</td>
									<td>재정라</td>
									<td>감치</td>
									<td>증인·채무자감치항고사건재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>283</td>
									<td>재정마</td>
									<td>감치</td>
									<td>증인·채무자감치재항고사건재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>284</td>
									<td>재정고</td>
									<td>감치</td>
									<td>법정질서위반감치등사건재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>285</td>
									<td>재정드</td>
									<td>감치</td>
									<td>의무불이행자감치등사건재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>286</td>
									<td>재정브</td>
									<td>감치</td>
									<td>의무불이행자감치등항고사건재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>287</td>
									<td>재정스</td>
									<td>감치</td>
									<td>의무불이행자감치등재항고사건재심</td>
									<td>X</td>
								</tr>
								<tr>
									<td>288</td>
									<td>재정기</td>
									<td>감치</td>
									<td>기타감치신청사건재심</td>
									<td>X</td>
								</tr>
								</tbody>
							</table>
						</div>
						<div class='case_sign' id='case_sign_11'>
							<table summary='코드, 사건구분, 사건유형, 내용, 사건검색 제공 별 사건구분안내 표'>
								<caption>사건구분안내 신청</caption>
								<colgroup>
									<col width='20%'>
									<col width='20%'>
									<col width='60%'>
									<col width='43%'>
									<col width='15%'>
								</colgroup>
								<thead>
								<tr>
									<th>코드</th>
									<th>
										사건
										구분
									</th>
									<th>
										사건
										유형
									</th>
									<th>내용</th>
									<th>
										사건
										검색
										제공
									</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td>008</td>
									<td>카</td>
									<td>신청</td>
									<td>
										<p>민사가압류,가처분등사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>069</td>
									<td>카공</td>
									<td>신청</td>
									<td>
										<p>공시최고사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>213</td>
									<td>카구</td>
									<td>신청</td>
									<td>
										<p>소송구조등사건</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>074</td>
									<td>카기</td>
									<td>신청</td>
									<td>
										<p>기타민사신청사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>401</td>
									<td>카기전</td>
									<td>신청</td>
									<td>
										<p>전자독촉사건 경정신청사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>072</td>
									<td>카단</td>
									<td>신청</td>
									<td>
										<p>민사가압류,가처분등단독사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>073</td>
									<td>카담</td>
									<td>신청</td>
									<td>
										<p>담보취소등사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>201</td>
									<td>카명</td>
									<td>신청</td>
									<td>
										<p>재산명시등사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>212</td>
									<td>카조</td>
									<td>신청</td>
									<td>
										<p>재산조회사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>071</td>
									<td>카합</td>
									<td>신청</td>
									<td>
										<p>민사가압류,가처분등합의사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>411</td>
									<td>카확</td>
									<td>신청</td>
									<td>
										<p>소송비용 확정을 위한 신청사건</p>
									</td>
									<td>○</td>
								</tr>
								<tr>
									<td>217</td>
									<td>재카구</td>
									<td>신청</td>
									<td>
										<p>소송구조등사건재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>192</td>
									<td>재카기</td>
									<td>신청</td>
									<td>
										<p>기타민사신청사건재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>190</td>
									<td>재카단</td>
									<td>신청</td>
									<td>
										<p>민사가압류,가처분등단독사건재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>191</td>
									<td>재카담</td>
									<td>신청</td>
									<td>
										<p>담보취소등사건재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>189</td>
									<td>재카합</td>
									<td>신청</td>
									<td>
										<p>민사가압류,가처분등합의사건재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>222</td>
									<td>준재카기</td>
									<td>신청</td>
									<td>
										<p>기타민사신청사건준재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>220</td>
									<td>준재카단</td>
									<td>신청</td>
									<td>
										<p>민사가압류,가처분등단독사건준재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>221</td>
									<td>준재카담</td>
									<td>신청</td>
									<td>
										<p>담보취소등사건준재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>219</td>
									<td>준재카합</td>
									<td>신청</td>
									<td>
										<p>민사가압류,가처분등합의사건준재심</p>
									</td>
									<td>X</td>
								</tr>
								<tr>
									<td>421</td>
									<td>카열</td>
									<td>신청</td>
									<td>
										<p>확정된 소송기록에 대한 열람신청사건</p>
									</td>
									<td>○</td>
								</tr>
								</tbody>
							</table>
						</div>
						<div class='case_sign' id='case_sign_12'>
							<table summary='코드, 사건구분, 사건유형, 내용, 사건검색 제공 별 사건구분안내 표'>
								<caption>사건구분안내 기타</caption>
								<colgroup>
									<col width='20%'>
									<col width='20%'>
									<col width='60%'>
									<col width='43%'>
									<col width='15%'>
								</colgroup>
								<thead>
								<tr>
									<th>코드</th>
									<th>
										사건
										구분
									</th>
									<th>
										사건
										유형
									</th>
									<th>내용</th>
									<th>
										사건
										검색
										제공
									</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td>193</td>
									<td>영장</td>
									<td>기타</td>
									<td>영장</td>
									<td>X</td>
								</tr>
								<tr>
									<td>400</td>
									<td>차전</td>
									<td>기타</td>
									<td>전자독촉사건</td>
									<td>○</td>
								</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div class='case_sign_law' style='display: none;'>
						<div class='normal'>
							<em>제1조</em>(목적)
							<br>이 예규는 법원재판사무처리규칙 제20조의 규정에 따라 사건별 부호문자(다음부터 '사건부호'라 한다)의 부여에 관하여 필요한 사항을 규정함을 목적으로 한다.
						</div>
						<div class='normal'>
							<em>제2조</em>(사건부호의 부여)
							<br>① 사건별 사건부호는 [별표]와 같다.

							<br>② 모든 재심사건(준재심사건을 포함한다)은 재심대상사건의 사건부호 앞에 '재'를 붙인다. 다만, 재심사건이 상소되는 경우 상소심의 사건부호는 원래의 사건부호
							앞에 '재'를 붙이지 아니한다.

							<br>③ 약식명령에 관한 재심사건이 공판절차에 회부되는 경우 공판사건의 사건부호는 원래의 사건부호 앞에 '재'를 붙이지 아니한다.
						</div>
						<div class='normal'>
							<em>제3조</em>(민사 및 가사신청사건이 상소심에서 제기되는 경우)
							<br>① 민사신청사건 중 가압류ㆍ가처분 및 이에 대한 이의, 취소(집행취소는 제외)사건이 항소심에서 제기되는 경우 사건부호는 '카합'으로 한다.<br>

							② 민사신청사건 중 권리행사최고, 담보취소, 권리행사최고 및 담보취소, 담보제공, 담보물변경 사건이 항소심 또는 상고심에서 제기되는 경우 사건부호는 '카담'으로
							한다.<br>

							③ 민사신청사건 중 소송구조, 구조취소사건이 항소심 또는 상고심에서 제기되는 경우 사건부호는 '카구'로 한다.<br>

							④ 기타 민사신청사건이 항소심 또는 상고심에서 제기되는 경우 사건부호는 '카기'로 한다.<br>

							⑤ 상소심에서 제기되는 가사신청사건 중 가압류ㆍ가처분 및 이에 대한 이의, 취소(집행취소는 제외)사건의 사건부호는 ‘즈합'으로 하고, 그 밖에 가사신청사건의
							사건부호는 ‘즈기’로 한다.
						</div>
						<div class="normal">
							<em>제4조</em>(반소 등이 항소심에서 제기되는 경우)
							<br>민사본안사건이 항소심에 계속중에 반소, 독립당사자참가 등 별도의 사건번호가 부여되는 사건이 제기되는 경우 사건부호는 '나'로 한다.
						</div>
						<div class="normal">
							<em>제5조</em>(항소심이 관할위반 형사사건을 제1심으로 심판하는 경우)
							<br>형사소송법 제367조 단서에 의하여 항소법원이 제1심으로 심판하는 경우의 사건부호는 '고합'으로 한다.
						</div>
						<div class="normal">
							<em>제6조</em>(고등법원이 제1심으로 관할하는 행정사건의 경우)
							<br>고등법원이 제1심으로 관할하는 행정사건이 고등법원에 제기되는 경우 사건부호는 '누'로 하며, 그 사건이 상고되는 경우 사건부호는 '두'로 한다.
						</div>
						<div class="normal">
							<em>제7조</em>(시ㆍ군법원이 관할하는 사건의 경우)
							<br>시ㆍ군법원이 민사소송법 및 민사집행법 등에 의하여 수소법원, 제1심 판결법원 또는 그 밖의 사유로 관할하는 사건이 시ㆍ군법원에 제기되는 경우 사건부호는 그
							사건의 종류에 따라 제2조 제1항의 [별표]에 규정된 바에 따른다.

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!--	끝 : 본문	-->
</body>
</html>
